### ISSUE TITLE
DARUSDT

### ISSUE THREAD

**Issue by jarrodjay** [cdalton713/trading-bot-new-coins#14]
Almost, but no cigar. 

The purchase was smooth with the exact amount going through! Placed the live order at 2021-11-04 08:00:01,958.
However, the API sent back that the price was "price": 2.49999997 (this isn't correct- it was $10. So, a second later when the API was checked and the price was 10.13766, it sold for what it thought was a decent profit (although there was not a profit). 

Also, I know you mentioned something about this elsewhere regarding the buy and sale quantity, but if the commission is coming out of BNB, why is the sale qty not the same as purchase qty? I know it's not much- but I purchased 4 DAR, but it only sold 3 DAR (due to the minimum step you mentioned previously), but all commissions are set to come out of BNB. That last DAR then crashed.

There wasn't enough in my wallet for the second coin, BNXUSDT.

**Comment by cdalton713** [comment]
I'm gonna bite the bullet and spend a few bucks testing live orders... I must be missing something obvious because these API responses aren't matching what I'm expecting from the documentation.

Since I made that change to purchase for an exact amount, I don't believe any of those calculations matter anymore, but I'll double-check too.

**Comment by cdalton713** [comment]
Was able to do some testing with actual responses, have a test case that's running everything successfully so the next token is looking better (be sure to update).

**Comment by jarrodjay** [comment]
Yeah, I forgot to pull update 🤦 
It was then trying to buy for the sell order, and luckily had no more money in my account. Pulled update now. Await next coin!

**Comment by cdalton713** [comment]
This coin executed everything correctly with the new update finally! (aside from the value dropping below SL).   I'm going to add in some more logging info today, but otherwise it's looking better.

**Comment by jarrodjay** [comment]
Any comment on the sell QTY not matching full buy QTY if BNB is being used as commission? Or perhaps a limitation with FTX?

**Comment by cdalton713** [comment]
Do you mean Binance, not FTX, right?

I'm not entirely sure where/how the fees come out of the account, esp if you have 0 BNB in your account (i.e. when you only have USDT).  I followed the logic in [this thread](https://github.com/sammchardy/python-binance/issues/219#issuecomment-534469928) to get the sales to work since Binance requires very specific number formatting for sales, based on the total value and the precision of the quantity you're trying to sell.    

For example, DARUSDT's filter requirements are:

```
{
  "filterType": "LOT_SIZE",
  "minQty": "1.00000000",
  "maxQty": "92141578.00000000",
  "stepSize": "1.00000000"
}
```

Meaning the minimum you can buy/sell is 1 and you can only sell whole numbers of it.  Since some small percentage of the total sale went to fees, the most you could get rid of is 3.  

If there's some way to avoid this and route the fees through BNB instead that'd definitely be better and I'd be happy to make the change though!

**Comment by jarrodjay** [comment]
Looking at the verbose log, it's taking the fees from BNB for me. Note the "commissionAsset" below. No idea what happens if there was no BNB though.
`[ERROR] 2021-11-05 06:00:01,925: {'symbol': 'RGTUSDT', 'orderId': 1162, 'orderListId': -1, 'clientOrderId': 'fDKngIZi8ATluzre8aj47j', 'transactTime': 1636092001921, 'price': '0.00000000', 'origQty': '0.50000000', 'executedQty': '0.50000000', 'cummulativeQuoteQty': '29.75000000', 'status': 'FILLED', 'timeInForce': 'GTC', 'type': 'MARKET', 'side': 'BUY', 'fills': [{'price': '59.50000000', 'qty': '0.50000000', 'commission': '0.00002934', 'commissionAsset': 'BNB', 'tradeId': 786}]`

**Comment by cdalton713** [comment]
Check out the `dev` branch - I've added a `USE_BNB_FOR_FEES` setting.  Basically, you need to make sure 'Use BNB for Fees' is enabled in the Binance Website, then turn this setting on.  If on, 100% of the coin will be sold rather than 99.9%.  

I'm not entirely convinced this is going to work; I'm sorta expecting to get a FILTER error with these changes so keep that in mind if you try running the dev branch.

**Comment by jarrodjay** [comment]
Legend! I've checked it out and will post back.

**Comment by cdalton713** [comment]
`dev` branch is now also testing an auto API rate manager.

**Comment by jarrodjay** [comment]
Something not quite right with the frontload settings now. It continues to sleep for 5 seconds regardless. Looked at your changes- but my brain is a bit frazzled atm (3 year old was up all night vomiting).

`FRONTLOAD_REQUESTS:
    FRONTLOAD_ENABLED: True
    FRONTLOAD_START: 58
    FRONTLOAD_DURATION: 6`

`[DEBUG] 2021-11-07 09:44:56,334: Loop finished in [0.055911] seconds.
[DEBUG] 2021-11-07 09:44:56,334: Request Weight: 163.
[DEBUG] 2021-11-07 09:44:56,334: Sleeping for [5] seconds.
[DEBUG] 2021-11-07 09:45:01,340: [BINANCE]	Getting all tickers...
[DEBUG] 2021-11-07 09:45:01,404: [BINANCE]	No new tickers found...
[DEBUG] 2021-11-07 09:45:01,405: Loop finished in [0.064692] seconds.`

**Comment by cdalton713** [comment]
Can you double check you have the latest version of dev?

I ended up working on it a good bit more after my comment yesterday. I think at one point I had the issue you're referring to but have since fixed it. 

New version has auto rate adjustments as well.

**Comment by jarrodjay** [comment]
Just did a pull- there was one small update with main.py, but problem persists.

`[DEBUG] 2021-11-08 00:20:56,533: [BINANCE]	Getting all tickers...
[DEBUG] 2021-11-08 00:20:56,591: [BINANCE]	No new tickers found...
[DEBUG] 2021-11-08 00:20:56,592: Loop finished in [0.058838] seconds.
[DEBUG] 2021-11-08 00:20:56,592: Request Weight: 434.
[DEBUG] 2021-11-08 00:20:56,592: Sleeping for [5] seconds.
[DEBUG] 2021-11-08 00:21:01,598: [BINANCE]	Getting all tickers...
[DEBUG] 2021-11-08 00:21:01,656: [BINANCE]	No new tickers found...
[DEBUG] 2021-11-08 00:21:01,657: Loop finished in [0.059429] seconds.`

**Comment by jarrodjay** [comment]
Just started from scratch to make sure there was nothing funny left, and recloned repo. 

Same issue. Not detecting correct time to start frontload.
```[DEBUG] 2021-11-08 00:28:55,068: [BINANCE]	Getting all tickers...
[DEBUG] 2021-11-08 00:28:55,129: [BINANCE]	No new tickers found...
[DEBUG] 2021-11-08 00:28:55,130: Loop finished in [0.062397] seconds.
[DEBUG] 2021-11-08 00:28:55,130: Request Weight: 71.
[DEBUG] 2021-11-08 00:28:55,131: Sleeping for [5] seconds.```

**Comment by cdalton713** [comment]
Oh I see - ok just pushed a fix.  Alo try reducing your frequency to 2, it should auto increase if needed.

**Comment by jarrodjay** [comment]
Fixed 👍 . Frontload duration is possibly misleading I believe. 6 actually equals up to 7. I guess it's currently min, not max.

Will test out the auto  rate increase!

**Comment by jarrodjay** [comment]
Setting it to 3 seconds, didn't actually increase my rate, just put seemingly annoyingly pauses in during frontloader. 
This one makes sense: 
```
[INFO] 2021-11-08 01:03:41,954: Bot request count above [75%] of rate limit
[INFO] 2021-11-08 01:03:41,954: Sleeping for [15] seconds until [2021-11-08 01:03:57.500000] to avoid exceeding rate limits
```

However, these not so much, as it's the pivotal time.
```
[DEBUG] 2021-11-08 01:05:58,234: [BINANCE]	Getting all tickers
[DEBUG] 2021-11-08 01:05:58,295: [BINANCE]	No new tickers found
[DEBUG] 2021-11-08 01:05:58,296: Loop finished in [0.061388] seconds
[DEBUG] 2021-11-08 01:05:58,296: Request Weight: 1090
[INFO] 2021-11-08 01:05:58,296: Bot request count above [85%] of rate limit
[INFO] 2021-11-08 01:05:58,296: Sleeping for [1] seconds until [2021-11-08 01:06:00] to avoid exceeding rate limits

[DEBUG] 2021-11-08 01:05:58,296: Sleeping for [1] seconds

[DEBUG] 2021-11-08 01:05:59,298: [BINANCE]	Getting all tickers
[DEBUG] 2021-11-08 01:05:59,370: [BINANCE]	No new tickers found
[DEBUG] 2021-11-08 01:05:59,371: Loop finished in [0.073116] seconds
[DEBUG] 2021-11-08 01:05:59,371: Request Weight: 1100
[INFO] 2021-11-08 01:05:59,371: Bot request count above [85%] of rate limit
[INFO] 2021-11-08 01:05:59,371: Sleeping for [1] seconds until [2021-11-08 01:06:00] to avoid exceeding rate limits

[DEBUG] 2021-11-08 01:05:59,371: Sleeping for [1] seconds

[DEBUG] 2021-11-08 01:06:00,373: [BINANCE]	Getting all tickers
[DEBUG] 2021-11-08 01:06:00,433: [BINANCE]	No new tickers found
[DEBUG] 2021-11-08 01:06:00,434: Loop finished in [0.06114] seconds
[DEBUG] 2021-11-08 01:06:00,434: Request Weight: 10
[DEBUG] 2021-11-08 01:06:00,434: Sleeping for [3] seconds
```

**Comment by cdalton713** [comment]
That's working correctly. The 85% limit is basically two more requested and you'll be rate limited, so it's stopping at a good time. 

Realistically, after a few minutes of runtime the program will likely increase your rate to 3.5 seconds, at which point it won't be rate limited during the normal or front load period.

**Comment by jarrodjay** [comment]
95% 👍 

It broke. 
```
[ERROR] 2021-11-08 01:59:59,127: Task exception was never retrieved
future: <Task finished name='Task-1' coro=<forever() done, defined at /home/ec2-user/trading-bot-new-coins/main.py:32> exception=ValueError('minute must be in 0..59')>
Traceback (most recent call last):
  File "/home/ec2-user/trading-bot-new-coins/main.py", line 51, in forever
    sleep_time = get_sleep_time(current_time)
  File "/home/ec2-user/trading-bot-new-coins/main.py", line 84, in get_sleep_time
    resume_time = datetime(
ValueError: minute must be in 0..59
```

**Comment by cdalton713** [comment]
Pushed update. It's been running all night with this change no problems.

**Comment by jarrodjay** [comment]
After a successful buy order last night, I'm getting this at every loop:

```
[DEBUG] 2021-11-08 21:15:14,235: [BINANCE]      Active Order Tickers: [{'MOVRUSDT': Order(broker='BINANCE', ticker=Ticker(ticker='MOVRUSDT', base_ticker='MOVR', quote_ticker='USDT'), purchase_datetime=datetime.datetime(2021, 11, 8, 6, 0, 0, 118324), price=487.99998194, side='BUY', size=0.04, type='market', status='LIVE', take_profit=inf, stop_loss=390.399985552, trailing_stop_loss_activated=False, trailing_stop_loss_max=658.799975619, trailing_stop_loss=439.199983746)}]
[DEBUG] 2021-11-08 21:15:14,235: Getting latest price for [ticker='MOVRUSDT' base_ticker='MOVR' quote_ticker='USDT']
[DEBUG] 2021-11-08 21:15:14,255: [BINANCE]      Getting all tickers
[DEBUG] 2021-11-08 21:15:14,314: [BINANCE]      No new tickers found
[DEBUG] 2021-11-08 21:15:14,315: Loop finished in [0.07983] seconds
```

It didn't sell though.

**Comment by cdalton713** [comment]
Remove it from BINANCE_OPEN_ORDERS.json

I need more info/logs for why it didn't sell.

**Comment by jarrodjay** [comment]
Yep, I've flushed the json. 

There's no logs for the selling though. No attempt seems to be have been made 😕 

```
2021-11-08 06:00:00,102: PROCESSING NEW TICKER:
{"ticker": "MOVRUSDT", "base_ticker": "MOVR", "quote_ticker": "USDT"}
2021-11-08 06:00:00,102: [BINANCE]      Preparing to buy MOVRUSDT
2021-11-08 06:00:00,102: [BINANCE]      Placing [LIVE] Order..
2021-11-08 06:00:00,118: {'symbol': 'MOVRUSDT', 'orderId': 114, 'orderListId': -1, 'clientOrderId': 'QcEsfXc4onjMVlbReC7K8a', 'transactTime': 1636351200111, 'price': '0.00000000', 'origQty': '0.04000000', 'executedQty': '0.04000000', 'cummulativeQuoteQty': '19.52000000', 'status': 'FILLED', 'timeInForce': 'GTC', 'type': 'MARKET', 'side': 'BUY', 'fills': [{'price': '488.00000000', 'qty': '0.04000000', 'commission': '0.00001806', 'commissionAsset': 'BNB', 'tradeId': 57}]}
2021-11-08 06:00:00,118: ORDER RESPONSE:
{"broker": "BINANCE", "ticker": {"ticker": "MOVRUSDT", "base_ticker": "MOVR", "quote_ticker": "USDT"}, "purchase_datetime": "2021-11-08T06:00:00.118324", "price": 487.99998194, "side": "BUY", "size": 0.04, "type": "market", "status": "LIVE", "take_profit": Infinity, "stop_loss": 390.399985552, "trailing_stop_loss_activated": false, "trailing_stop_loss_max": 658.799975619, "trailing_stop_loss": 439.199983746}
```

**Comment by cdalton713** [comment]
I think it worked fine... look at the price history of the coin.  The coin never reached your trailing stop lost activation price of $658.78.  Additionally, it never went below your stop loss amount until less than an hour ago after you deleted the JSON file.  It was correctly holding between those prices.  Please be sure to check all this out!

**Comment by jarrodjay** [comment]
Everything working perfectly, great job! Just can't catch the price early enough. 

When your notification service informs discord of the position being closed, it uses the initial buy price, rather than the sell price. I don't use TG notification, so not sure.

```
Trading-Bot
BOT
 — Today at 9:00 PM
NEW POSITION

    Broker: BINANCE
    Datetime: 2021-11-12 10:00:00.113416
    Status: LIVE

    Ticker: KP3RUSDT
    Amount: 0.02
    Price: 1143.0
Trading-Bot
BOT
 — Today at 9:28 PM
POSITION CLOSED

    Broker: BINANCE
    Datetime: 2021-11-12 10:00:00.113416
    Status: LIVE

    Ticker: KP3RUSDT
    Amount: 0.02
    Price: 1143.0
```

**Comment by cdalton713** [comment]
Fixed for next push. Closing this!
