### ISSUE TITLE
Verbose log shows errors, coin was bought and sold within seconds

### ISSUE THREAD

**Issue by donmega** [cdalton713/trading-bot-new-coins#19]
Hi, great bot! Keep up the good work!

I was wondering if everything went right. As far as i can see the order was opened and closed within seconds. I an running the newest build. The verbose log also shows ERROR a couple of times:

```
[ERROR] 2021-11-05 06:00:00,265: PROCESSING NEW TICKER:
{"ticker": "RGTUSDT", "base_ticker": "RGT", "quote_ticker": "USDT"}.
[ERROR] 2021-11-05 06:00:00,266: [BINANCE]	Preparing to buy RGTUSDT.
[ERROR] 2021-11-05 06:00:00,266: [BINANCE]	Placing [LIVE] Order...
[ERROR] 2021-11-05 06:00:00,339: {'symbol': 'RGTUSDT', 'orderId': 212, 'orderListId': -1, 'clientOrderId': 'frPH9cj9M56zs3d360xtVJ', 'transactTime': 1636092000297, 'price': '0.00000000', 'origQty': '1.66000000', 'executedQty': '1.66000000', 'cummulativeQuoteQty': '99.43400000', 'status': 'FILLED', 'timeInForce': 'GTC', 'type': 'MARKET', 'side': 'BUY', 'fills': [{'price': '59.90000000', 'qty': '1.66000000', 'commission': '0.00009743', 'commissionAsset': 'BNB', 'tradeId': 112}]}.
[ERROR] 2021-11-05 06:00:00,340: ORDER RESPONSE:
{"broker": "BINANCE", "ticker": {"ticker": "RGTUSDT", "base_ticker": "RGT", "quote_ticker": "USDT"}, "purchase_datetime": "2021-11-05T06:00:00.339822", "price": 59.89990257, "side": "BUY", "size": 1.66, "type": "market", "status": "LIVE", "take_profit": Infinity, "stop_loss": 47.919922056000004, "trailing_stop_loss_max": -Infinity, "trailing_stop_loss": 53.909912313}.
[ERROR] 2021-11-05 06:00:04,647: [BINANCE]	[RGTUSDT] Updated:
	Trailing Stop-Loss: 53.91 .
[ERROR] 2021-11-05 06:00:05,007: CLOSING Order:
{"broker": "BINANCE", "ticker": {"ticker": "RGTUSDT", "base_ticker": "RGT", "quote_ticker": "USDT"}, "purchase_datetime": "2021-11-05T06:00:00.339822", "price": 59.89990257, "side": "BUY", "size": 1.66, "type": "market", "status": "LIVE", "take_profit": Infinity, "stop_loss": 47.919922056000004, "trailing_stop_loss_max": 59.89990257, "trailing_stop_loss": 53.909912313}.
[ERROR] 2021-11-05 06:00:05,008: Current Price:	50.47.
[ERROR] 2021-11-05 06:00:05,008: Stored Price:	59.89990257.
[ERROR] 2021-11-05 06:00:05,208: {'symbol': 'RGTUSDT', 'orderId': 3040, 'orderListId': -1, 'clientOrderId': 'WE1ZrDG1YZUL0d16pHGJay', 'transactTime': 1636092005165, 'price': '0.00000000', 'origQty': '1.66000000', 'executedQty': '1.66000000', 'cummulativeQuoteQty': '82.23640000', 'status': 'FILLED', 'timeInForce': 'GTC', 'type': 'MARKET', 'side': 'SELL', 'fills': [{'price': '49.54000000', 'qty': '1.66000000', 'commission': '0.00010497', 'commissionAsset': 'BNB', 'tradeId': 2439}]}.
[ERROR] 2021-11-05 06:00:05,413: SOLD:
{"broker": "BINANCE", "ticker": {"ticker": "RGTUSDT", "base_ticker": "RGT", "quote_ticker": "USDT"}, "purchase_datetime": "2021-11-05T06:00:00.339822", "price": 49.53989503, "side": "SELL", "size": 1.66, "type": "market", "status": "LIVE", "take_profit": Infinity, "stop_loss": 39.631916024, "trailing_stop_loss_max": -Infinity, "trailing_stop_loss": 44.585905526999994, "profit": -15.653638266200005, "profit_percent": -15.742767793286585, "sold_datetime": "2021-11-05T06:00:05.208850"}.```

**Comment by jarrodjay** [comment]
All looks good (apart from the loss, of course!). Think just the way he's set up logging. They're not actually errors :)

**Comment by cdalton713** [comment]
That looks correct - you purchased it at 59.8999 but the price immediately dropped below the trailing stop loss.  

I just changed how this works today however, now the trailing stop loss won't activate unless the price goes above the activation price.  It'll still sell if it goes below the regular stop-loss though.

Speed is very important for this app to be successful.  @jarrodjay  has been pushing its limits and reducing lag with a VPS, perhaps he'd be willing to share his setup and add it to the readme (I'm curious as well)?

**Comment by HavaneFr** [comment]
how can we see if the speed is enought ? Hi have for exemple Loop finished in [0.5449895858764648] seconds.

**Comment by jarrodjay** [comment]
Happy to share my setup later today. My loops finish in around [0.0576014518737793] seconds, so 10x faster. I've only had one successful buy/sell, but time is of the essence.

**Comment by jarrodjay** [comment]
AVG TIME PER LOOP: 0.06741302121769298
TOTAL LOOPS: 44
(Nice addition @cdalton713!)

**Comment by jarrodjay** [comment]
I tested a dedicated server in CA, and in AU, and found that neither were fantastic. Also tested my personal connection in AU. Decided to make use of Amazon's EC2 and their free 750 hours per month for 1 year tier. Best DC I've found is ap-northeast-1a. Spin up a t2.micro instance, set up the security pairs, set up the trading-bot. I saved an image at this point, so I could instantly spin up the already set up instance when needed (be mindful of the binance API and the set iP if doing this, unless using an elastic IP).

**Comment by HavaneFr** [comment]
What do you mean by "set up the security pairs"?

**Comment by jarrodjay** [comment]
> What do you mean by "set up the security pairs"?

With EC2, the only way to SSH into an instance is to set up security/key pairs.
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-key-pairs.html

**Comment by HavaneFr** [comment]
> I tested a dedicated server in CA, and in AU, and found that neither were fantastic. Also tested my personal connection in AU. Decided to make use of Amazon's EC2 and their free 750 hours per month for 1 year tier. Best DC I've found is ap-northeast-1a. Spin up a t2.micro instance, set up the security pairs, set up the trading-bot. I saved an image at this point, so I could instantly spin up the already set up instance when needed (be mindful of the binance API and the set iP if doing this, unless using an elastic IP).

Under Linux?

**Comment by cdalton713** [comment]
@HavaneFr  see the updated readme for steps

**Comment by jarrodjay** [comment]
> @HavaneFr see the updated readme for steps

Perfect. Waiting for some profit on a trade so I can chuck some towards you too.

**Comment by donmega** [comment]
Thanks for the fix!

**Comment by HavaneFr** [comment]
> @HavaneFr see the updated readme for steps

It works : 0.1 s for ftx only 
I needed more steps than in your read.me, for exemple : 

sudo apt-get update
sudo apt install python3-pip
pip install gitpython

installing requirements
