### ISSUE TITLE
Live order failed with Filter failure: LOT_SIZE - can't see in the log file the exact order request submitted

### ISSUE THREAD

**Issue by lourencor** [cdalton713/trading-bot-new-coins#23]
I am running the bot in LIVE mode and got this error today.

After looking at the logs, I can't find the exact order that was placed in the log file, to understand what the problem was. I see in the google search that this is due to a possible misconfiguration of the amounts, but I couldn't point out what it is.

I also wanted to ask if it is possible to log the order creation requests, so I can see exactly what the bot is trying to place in Binance - amount, quantity, TP and SL, and so on.

```Traceback (most recent call last):
  File "/home/ubuntu/trading_bots/trading-bot-new-coins/bot/bot.py", line 322, in process_new_ticker
    order = self.broker.place_order(
  File "/home/ubuntu/trading_bots/trading-bot-new-coins/broker/broker.py", line 333, in place_order
    api_resp = super(Binance, self).create_order(**params)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/binance/client.py", line 1387, in create_order
    return self._post('order', True, data=params)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/binance/client.py", line 374, in _post
    return self._request_api('post', path, signed, version, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/binance/client.py", line 334, in _request_api
    return self._request(method, uri, signed, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/binance/client.py", line 315, in _request
    return self._handle_response(self.response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/binance/client.py", line 324, in _handle_response
    raise BinanceAPIException(response, response.status_code, response.text)
binance.exceptions.BinanceAPIException: APIError(code=-2010): Filter failure: LOT_SIZE
```
[errors.log](https://github.com/cdalton713/trading-bot-new-coins/files/7528143/errors.log)
[config.yml.txt](https://github.com/cdalton713/trading-bot-new-coins/files/7528153/config.yml.txt)

**Comment by cdalton713** [comment]
Hello,

I'm pretty fairly certain it's because your quantity is too low - Binance only allows orders greater than
$10.00 USDT (or around that). I'll add that limitation to the readme. I have a check for this in the program but it didn't trigger for some reason on yours, I'll look into why...

Ideally you'll want to use a quantity wherein the dollar value of your stop loss (at X% that of your choosing) is greater than 10; $12 or so SL would be a safe number probably. 

I'll also add that logging.

**Comment by lourencor** [comment]
It is a good point, I have pulled latest code and applied the changes to the config.yml.
However, even at 13$ it still shows this message:

```Your stop loss value of [13 - (1 - 0.2) = $10.4] is less than or around $10.00. If a Stop Loss is triggered and the market value is less than $10.00 Binance will likely deny the sale.```

Only at 15$ did the message disappear. And I have activated BNB for fees.

**Comment by cdalton713** [comment]
Anything less than 12$ calculated stop loss will give that warning. Since the market price may be less than your SL when the SL sale triggers I wanted to leave a bit of a buffer. You can see the code in broker.py and change if you'd like.
