### ISSUE TITLE
the order is always executed when the price is back

### ISSUE THREAD

**Issue by oularrea** [cdalton713/trading-bot-new-coins#29]
**Describe the bug**
Hello good, first of all I want to thank you for sharing your code with the community, the truth that I love the solution and I appreciate the effort you make.

I write because I have already been testing the bot in several currencies in binance and I always have the same problem, that although the bot buys in the second 00 that the coin comes out, the order is always executed when the price peak has already risen to the maximum and the price is returning.

I leave you some of the examples that have happened to us these days

Note: I have the AWS where your recommendations and it goes very well with respect to the local computer

**Error Log**
the order is always executed when the price is back

NEW POSITION

    Broker: BINANCE
    Datetime: 2021-12-01 12:00:00.254276
    Status: LIVE

    Ticker: SANTOSUSDT
    Amount: 3.01
    Price: 19.899
    
    POSITION CLOSED

    Broker: BINANCE
    Datetime: 2021-12-01 12:00:02.616857
    Status: LIVE
    Reason: PRICE_BELOW_SL

    Ticker: SANTOSUSDT
    Amount: 3.01
    Price: 17.8759
    Profit: -4.0966
    Profit Percent: -6.8395

POSITION CLOSED

    Broker: BINANCE
    Datetime: 2021-11-27 11:00:02.710014
    Status: LIVE
    Reason: PRICE_BELOW_SL

    Ticker: RNDRBUSD
    Amount: 5.42
    Price: 7.201
    Profit: -0.9754
    Profit Percent: -2.4385

NEW POSITION

    Broker: BINANCE
    Datetime: 2021-11-23 07:00:00.216189
    Status: LIVE

    Ticker: AMPUSDT
    Amount: 666.0
    Price: 0.075

NEW POSITION

    Broker: BINANCE
    Datetime: 2021-11-22 07:00:00.174953
    Status: LIVE

    Ticker: VGXUSDT
    Amount: 2.8
    Price: 5.3312

NEW POSITION

    Broker: BINANCE
    Datetime: 2021-11-26 08:00:00.322205
    Status: LIVE

    Ticker: PYRUSDT
    Amount: 0.352
    Price: 36.8996

Sugerencia: Suggestion: Do not you think that instead of placing a Market type order, if we place a Limit order with the price that has been listed plus 10% with this, at least if it is not executed, no money is lost, but to be executed it should not wait for the previous orders placed in the Market to be executed, that is, you do not have to wait for the order queue

**Comment by cdalton713** [comment]
I believe many of us are experiencing this 'issue' - to a certain extent, I think a lot of chance is involved with respect to which entry price you get.  See #28, hopefully, we can get feedback and more ideas like the one you suggested.

**Comment by IternaAdolfo** [comment]
I saw someone can buy at 3.x USDT here, so, did they have better server or they have an other method to detect new listing?
![someonecanbuyat3 5](https://user-images.githubusercontent.com/1461352/147376780-559583ce-2ff9-4e59-b9bc-803588af04c3.png)
