### ISSUE TITLE
Issue since latest pull

### ISSUE THREAD

**Issue by jarrodjay** [cdalton713/trading-bot-new-coins#8]
Since latest update and utilising submodules, I'm having the following issue:

```
root@binance:~/trading-bot-new-coins# python3 main.py
NEW UPDATE USES SUBMODULES!! These were just installed. Rerun program.
```

I've tried updating original cloned git, and starting fresh. I'm unsure what I'm needing to do, sorry.

**Comment by cdalton713** [comment]
@jarrodjay I just did a fresh pull of the latest main branch onto a Ubuntu 20.04 install without any issues.  Be sure to follow these steps:

1. **Clone** (don't just download the zip) repo to a folder.  Cloning includes the .git folder, downloading the repo does not.
2. Install requirements: `python3 pip install -r requirements.txt`
3. Run the main file: `python3 main.py`.  It should then tell you to rerun again.
4. Run the main file again: `python3 main.py`.  
5. Should be good to go!

If this doesn't work, I'd recommend adding this line after line 12 in util/config.py: `raise`.  This will raise the exception and give us more information about what's wrong.

Here's a screenshot of all of the files that should be in the multiNotification folder:
![Image 2021-10-08 23-02-18](https://user-images.githubusercontent.com/26048694/136643519-ab36d0db-94cb-4419-bbf1-a9d03248b60c.png)

**Comment by jarrodjay** [comment]
Thanks  Christian. I'm a Python pre-noob, and didn't know I needed to run `pip install -r requirements.txt`. I was reactively installing modules based on errors. After installing libpython3.9-dev, I was able to successfully install all requirements and bot is running again. 

Having said that, all trades that have been made so far using the bot, none of them have sold, had stop limits created, or been written in the log. Perhaps something to do with missing requirements above? We'll see how it goes now. 

I've also found that the highest freq I can run out without being rate limited, is 0.28. This doesn't seem quick enough to actually catch a new coin. Do you find that too?

Thanks for your help, love your work.

**Comment by cdalton713** [comment]
Glad you got it! Admittedly, I have had a few bugs with processing the live orders JSON response so far, so I doubt it was anything you did (it's hard to catch everything with only one new coin a week). Fortunately, I think I fixed them all after the last token launch this past week/this version - I'm waiting for the next token myself to see. 

As for the refresh speed - you've been using it at a much faster rate than me so I can't say.  But you did just gave me a new idea; I may be able to auto-adjust the rate to refresh as fast as possible without getting rate limited.  I'll look into this next week sometime!

**Comment by jarrodjay** [comment]
I bet! Happy to go along for the ride and help out where I can (which is very limited! Ha).

Definitely a great idea to add an auto-adjust to the rate, wouldn't be hard to calculate the weighted rate and keep track of how many per minute.

Another awesome addition to your fork could be scraping, which would enable flooding of requests at the specified minute of coin release. Lautaro-L did some work with this if you're interested - https://github.com/Lautaro-L/Binance_New_Coins_Scraper/blob/main/main.py
